version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "deps"
      include: "scope"
    rebase-strategy: auto
    groups:
      npm-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
      npm-major:
        update-types:
          - "major"

  - package-ecosystem: "gradle"
    directory: "/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "deps"
      include: "scope"
    rebase-strategy: auto
    groups:
      gradle-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
      gradle-major:
        update-types:
          - "major"

  - package-ecosystem: "pip"
    directory: "/genai"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "deps"
      include: "scope"
    rebase-strategy: auto
    groups:
      pip-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
      pip-major:
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    groups:
      actions-updates:
        update-types:
          - "minor"
          - "patch"
          - "major"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    groups:
      docker-updates:
        update-types:
          - "minor"
          - "patch"
          - "major"