apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: "{{ .Values.tumid }}-devops26"
spec:
  selector:
    app: account-service-selector
  ports:
    - port: {{ .Values.accountService.service.port }}
      targetPort: {{ .Values.accountService.service.targetPort }}
      protocol: TCP
  type: {{ .Values.accountService.service.type }}
