apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.accountService.replicaCount }}
  selector:
    matchLabels:
      app: account-service-selector
  template:
    metadata:
      labels:
        app: account-service-selector
    spec:
      containers:
        - name: account-service
          image: "{{ .Values.accountService.image.repository }}:{{ .Values.accountService.image.tag }}"
          imagePullPolicy: {{ $.Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.accountService.service.targetPort }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:{{ .Values.postgres.service.port }}/{{ .Values.postgres.database.name }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: "{{ .Values.postgres.database.user }}"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
          resources:
            {{- toYaml .Values.accountService.resources | nindent 12 }}
