apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-service
  namespace: { { .Release.Namespace | quote } }
spec:
  replicas: { { .Values.bankingService.replicaCount } }
  selector:
    matchLabels:
      app: banking-service-selector
  template:
    metadata:
      annotations:
        checksum/config: { { include "banking-app.rolloutChecksum" . } }
      labels:
        app: banking-service-selector
    spec:
      containers:
        - name: banking-service
          image: "{{ .Values.bankingService.image.repository }}:{{ .Values.bankingService.image.tag }}"
          imagePullPolicy: { { $.Values.imagePullPolicy } }
          ports:
            - containerPort: { { .Values.bankingService.service.targetPort } }
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:{{ .Values.postgres.service.port }}/{{ .Values.postgres.database.name }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: "{{ .Values.postgres.database.user }}"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: ENABLE_BANKING_APP_ID
              value: "{{ .Values.bankingService.enableBanking.appId }}"
            - name: ENABLE_BANKING_PRIVATE_KEY_PATH
              value: "{{ .Values.bankingService.enableBanking.privateKeyPath }}"
            - name: ENABLE_BANKING_REDIRECT_URL
              value: "{{ .Values.bankingService.enableBanking.redirectUrl }}"
            - name: ENABLE_BANKING_BASE_URL
              value: "{{ .Values.bankingService.enableBanking.baseUrl }}"
          resources:
            { { - toYaml .Values.bankingService.resources | nindent 12 } }
