apiVersion: v1
kind: Service
metadata:
  name: banking-service
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    app: banking-service-selector
  ports:
    - name: http
      port: {{ .Values.bankingService.service.port }}
      targetPort: {{ .Values.bankingService.service.targetPort }}
      protocol: TCP
  type: {{ .Values.bankingService.service.type }}
