apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-service
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.bankingService.replicaCount }}
  selector:
    matchLabels:
      app: banking-service-selector
  template:
    metadata:
      annotations:
        checksum/config: {{ include "banking-app.rolloutChecksum" . }}
      labels:
        app: banking-service-selector
        monitoring: "true"
    spec:
      containers:
        - name: banking-service
          image: "{{ .Values.bankingService.image.repository }}:{{ .Values.bankingService.image.tag }}"
          imagePullPolicy: {{ $.Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.bankingService.service.targetPort }}
          env:
            - name: SERVER_PORT
              value: "{{ .Values.bankingService.service.port }}"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:{{ .Values.postgres.service.port }}/{{ .Values.postgres.database.name }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: "{{ .Values.postgres.database.user }}"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
          resources:
            {{- toYaml .Values.bankingService.resources | nindent 12 }}
