apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: { { .Release.Namespace | quote } }
data:
  api_url: /api
  account_service_url: http://account-service:{{ .Values.accountService.service.port }}
  transaction_service_url: http://transaction-service:{{ .Values.transactionService.service.port }}
  orchestrator_service_url: http://orchestrator-service:{{ .Values.orchestratorService.service.port }}
  genai_service_url: http://genai-service:{{ .Values.genaiService.service.port }}
