apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-service
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.genaiService.replicaCount }}
  selector:
    matchLabels:
      app: genai-service-selector
  template:
    metadata:
      annotations:
        checksum/config: {{ include "banking-app.rolloutChecksum" . }}
      labels:
        app: genai-service-selector
        monitoring: "true"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: genai-service
          image: "{{ .Values.genaiService.image.repository }}:{{ .Values.genaiService.image.tag }}"
          imagePullPolicy: {{ $.Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.genaiService.service.targetPort }}
          env:
            - name: MODEL_PROVIDER
              value: "local"
          resources:
            {{- toYaml .Values.genaiService.resources | nindent 12 }}
