{{- if .Values.monitoring.grafana.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
stringData:
  admin-user: {{ .Values.monitoring.grafana.adminUser }}
  admin-password: {{ .Values.monitoring.grafana.adminPassword }}
{{- end }}
