{{- if .Values.monitoring.grafana.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ .Release.Namespace | quote }}
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:{{ .Values.monitoring.prometheus.service.port }}/prometheus
        isDefault: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: {{ .Release.Namespace | quote }}
data:
  dashboard.yml: |
    apiVersion: 1
    providers:
      - name: Banking Dashboards
        folder: Banking
        type: file
        options:
          path: /etc/grafana/provisioning/dashboards
  banking-overview.json: |
{{ .Files.Get "files/dashboards/banking-overview.json" | indent 4 }}
{{- end }}
