apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.transactionService.replicaCount }}
  selector:
    matchLabels:
      app: transaction-service-selector
  template:
    metadata:
      annotations:
        checksum/config: {{ include "banking-app.rolloutChecksum" . }}
      labels:
        app: transaction-service-selector
        monitoring: "true"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: transaction-service
          image: "{{ .Values.transactionService.image.repository }}:{{ .Values.transactionService.image.tag }}"
          imagePullPolicy: {{ $.Values.imagePullPolicy }}
          ports:
            - containerPort:
                {{ .Values.transactionService.service.targetPort }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:{{ .Values.postgres.service.port }}/{{ .Values.postgres.database.name }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: "{{ .Values.postgres.database.user }}"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
          resources:
            {{- toYaml .Values.transactionService.resources | nindent 12 }}
