apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    app: transaction-service-selector
  ports:
    - name: http
      port: {{ .Values.transactionService.service.port }}
      targetPort: {{ .Values.transactionService.service.targetPort }}
      protocol: TCP
  type: {{ .Values.transactionService.service.type }}
