apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: "{{ .Values.tumid }}-devops26"
spec:
  selector:
    app: transaction-service-selector
  ports:
    - port: {{ .Values.transactionService.service.port }}
      targetPort: {{ .Values.transactionService.service.targetPort }}
      protocol: TCP
  type: {{ .Values.transactionService.service.type }}
