/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "team-team"
include(":orchestrator-service")
include(":account-service")
include(":transaction-service")
project(":orchestrator-service").projectDir = file("server/orchestrator-service")
project(":account-service").projectDir = file("server/account-service")
project(":transaction-service").projectDir = file("server/transaction-service")
