/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.springframework.boot")
}

dependencies {
    implementation(libs.org.springframework.boot.spring.boot.starter.web)
    implementation(libs.org.springframework.boot.spring.boot.starter.webflux)
    implementation(libs.org.springframework.boot.spring.boot.starter.actuator)
    implementation(libs.org.springdoc.springdoc.openapi.starter.webmvc.ui)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation(libs.com.squareup.okhttp3.mockwebserver)

    implementation(libs.io.micrometer.micrometer.registry.prometheus)
    testImplementation("org.springframework.boot:spring-boot-starter-webmvc-test")
}

description = "orchestrator-service"
