/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
    implementation(libs.org.springframework.boot.spring.boot.starter.web)
    implementation(libs.org.springframework.boot.spring.boot.starter.actuator)
    implementation(libs.org.springdoc.springdoc.openapi.starter.webmvc.ui)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    implementation(libs.io.micrometer.micrometer.registry.prometheus)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
}

description = "orchestrator-service"
