/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "team-team"
include(":orchestrator-service")
include(":account-service")
include(":transaction-service")
project(":orchestrator-service").projectDir = file("orchestrator-service")
project(":account-service").projectDir = file("account-service")
project(":transaction-service").projectDir = file("transaction-service")
