http:

  routers:

    api:
      rule: "PathPrefix(`/api`)"
      priority: 90
      entryPoints:
        - websecure
      service: api-service
      tls:
        certResolver: letsencrypt

    frontend:
      rule: "PathPrefix(`/`)"
      priority: 1
      entryPoints:
        - websecure
      service: frontend-service
      middlewares:
        - compress
      tls:
        certResolver: letsencrypt

    grafana:
      rule: "PathPrefix(`/grafana`)"
      priority: 100
      entryPoints:
        - websecure
      service: grafana-service
      tls:
        certResolver: letsencrypt

    swagger:
      rule: "PathPrefix(`/swagger-ui`)"
      priority: 80
      entryPoints:
        - websecure
      service: api-service
      tls:
        certResolver: letsencrypt

    openapi:
      rule: "PathPrefix(`/v3/api-docs`)"
      priority: 70
      entryPoints:
        - websecure
      service: api-service
      tls:
        certResolver: letsencrypt


  services:

    api-service:
      loadBalancer:
        servers:
          - url: "http://orchestrator-service:8083"

    frontend-service:
      loadBalancer:
        servers:
          - url: "http://client:80"

    grafana-service:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"


  middlewares:

    compress:
      compress: {}